### ISSUE TITLE
Allow metadata to be added to compile targets

### ISSUE THREAD

**Issue by taharah** [kapicorp/kapitan#365]
**Describe the feature**

Allow metadata to be added to each compile target. For instance, setting a "name" that could be used to get the top level key for the inventory data used in the component(s). It would allow components to be written in a way that is much more usable than what is possible currently.

Current state:

```yaml
parameters:
  kapitan:
    compile:
    - output_path: <output_path_in_target_dir>
      input_type: jinja | jsonnet | kadet | helm
      input_paths:
        - path/to/input/dir/or/file
      output_type: <output_type_specific_to_input_type>
```

Adding a block similar to the following:

```yaml
parameters:
  kapitan:
    compile:
    - output_path: <output_path_in_target_dir>
      input_type: jinja | jsonnet | kadet | helm
      input_paths:
        - path/to/input/dir/or/file
      output_type: <output_type_specific_to_input_type>
      metadata:
        name: my_special_name
        version: v1.1.0
```

The metadata could then be referenced in each component:

```
local kap = import "lib/kapitan.libjsonnet";
local inventory = kap.inventory();
local metadata = kap.metadata();

{
    "data_java_opts": inventory.parameters[metadata.name].roles.data.java_opts,
}
```

**Comment by uberspot** [comment]
How does this approach compare with a basic one like:
```
parameters:
  metadata:
    name: my_special_name
    version: v1.1.0
```
and then referencing it as:
`    "data_java_opts": inventory.parameters[parameters.metadata.name].roles.data.java_opts,` ? 

The usual usage patterns we've seen with kapitan most of the time define a "common.yml" class which all targets inherit and it makes it easy to globally distribute any type of generic configuration, but still gives you the flexibility of overwriting anything you want in specific targets. I'm not sure it that would be possible with the above approach.

**Comment by taharah** [comment]
The main difference would that this would allow the metadata to be set per compile input rather than for the entire target. This would allow someone to reference the same component input(s), but end up compiling entirely different outputs by being able to flex the inventory data referenced via the metadata.

**Comment by uberspot** [comment]
This is basically polymorphism but with the inventory. You can also do that per component by just inheriting a common class in all your component yml's in the inventory and overwrite it only when necessary in some targets.
We do something similar in our infrastructure to change args in k8s deployments per target, but also have a set of "base" global args that we ship to all targets.

I'm not against the metadata keyword either. I'm just clarifying because it seems that Kapitan would become slightly opinionated to make polymorphism easier (usability-wise). 

I'm curious how many people would find this easier. 
If people can up/downvote on the first post it would help prioritize. :)

**Comment by taharah** [comment]
@uberspot I'm more than happy to take on the PR, if there is interest.

**Comment by uberspot** [comment]
Feel free too. :) We're happy to review.

**Comment by ademariag** [comment]
@taharah I proposed the same idea some time ago but with a slight variation.

```
parameters:
  kapitan:
    compile:
    - output_path: <output_path_in_target_dir>
      input_type: jinja | jsonnet | kadet | helm
      input_paths:
        - { file: path_to_shared_code, metadata: {name: "myspecialname"}}
      output_type: <output_type_specific_to_input_type>
```

the reason is that this would allow us to reuse components much more easily. Look at the following:

## shared config
```
parameters:
  manifests: []
  kapitan:
    compile:
    - output_path: <output_path_in_target_dir>
      input_type: jinja | jsonnet | kadet | helm
      input_paths: ${manifests}
      output_type: <output_type_specific_to_input_type>
```

## componentA
```
parameters:
  manifests:
    - { file: path_to_shared_code, metadata: {name: "componentA"}}

  components:
    componentA:
      image: my_image
```

## componentB
```
parameters:
  manifests:
    - { file: path_to_shared_code, metadata: {name: "componentB"}}

  components:
    componentB:
      image: my_image
```
