### ISSUE TITLE
[[Feature]]] Add ability to use jinja2 templates under components

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#678]
**Describe the bug/feature**
As we share the same story from where we come from (k8s templating wise) we'd liike to keep our jinja2 files instead rewriting everything in jsonnet nor kadet [DOCs](https://github.com/deepmind/kapitan/blob/master/docs/example-kubernetes.md#components).
Please add if possible the usage of jinja2 here.

_NOTE 
I'm just starting to figure out how kapitan works._

**To Reproduce**
1. Go to `/components/`
2. Create a `jinja2` template `namespace.j2`
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    name: {{ inventory.parameters.namespace }}
  name: {{ inventory.parameters.namespace }}
  namespace: {{ inventory.parameters.namespace }}
spec: {}
```
3. Add `/inventory/classes/component/namespace.yml`
```yaml
parameters:
  namespace: ${target_name}
  kapitan:
    compile:
    - output_path: pre-deploy
      input_type: jinja2
      output_type: yml
      input_paths:
        - components/namespace/namespace.j2
```
4. Run `kapitan compile`
5. `ls -lsah /compiled/k8s-infra/pre-deploy`
```bash
namespace.j2
```
6. Discover that it is rendered correctly

**Expected behavior**
I expected that the file is renamed. in the output format ending -> `namespace.yaml` or `namespace.yml`.

**Screenshots**
If applicable, add screenshots to help explain your problem/idea.

** If it's a bug (please complete the following information):**
 ```
 $ python --version
Python 3.8.
```
```
$ pip3 --version
pip 20.3.3 from /home/danny/.env3/lib/python3.8/site-packages/pip (python 3.8)
```
 - `Are you using pyenv or virtualenv?` - yes

**Additional context**
None.
