### ISSUE TITLE
Implement some sort of self reference to inventory

### ISSUE THREAD

**Issue by bsda** [kapicorp/kapitan#706]
**Describe the bug/feature**
It would save us a lot of duplication if we could have some sort of ${self} reference to the inventory

**To Reproduce**
For example:
I need to add this configmap to multiple components:

```
config_maps:
  monitoring-registry:
    mount: /opt/spinnaker-monitoring/registry
    data:
      igor.yml:
        value: "metrics_url: http://localhost:8088/spectator/metrics"
```

The port is the only thing that changes per component

Having the capacity of using something like this would be helpful:

```
value:  "metrics_url: http://localhost:${self:ports:http:service_port}/spectator/metrics"
```

The value in this case would reference to
```
parameters:
  components:
    spin-igor:
       ...
      ports:
        http:
          service_port: 8088

```

**Additional context**
I'm guessing this is one for the reclass package but I couldn't create issues there
