### ISSUE TITLE
Support unpacking dependencies of type "application/x-compressed"

### ISSUE THREAD

**Issue by jperville** [kapicorp/kapitan#730]
**Describe the bug/feature**

I recently tried to build one of my project that used to compile.
As of today the build fails shortly after emitting the following warning:

```
Dependency https://charts.jetstack.io/charts/cert-manager-v0.11.0.tgz : Content-Type application/x-compressed is not supported for unpack. Ignoring save
```

**To Reproduce**

I declared a helm dependency in my inventory file that looks like this:

```yaml
parameters:
  cert_manager:
    namespace: cert-manager
    # version must be valid release/tag name from https://github.com/jetstack/cert-manager
    version: v0.11.0

  kapitan:
    dependencies:
    - type: https
      source: https://charts.jetstack.io/charts/cert-manager-${cert_manager:version}.tgz
      unpack: true
      output_path: vendor/charts
```

**Expected behavior**

I expect the build to succeed.

**Screenshots**

```sh
$ scripts/build.sh my-kapitan-builder:1.0.0-alpha.7 sandbox-labs.yml

Dependency https://charts.jetstack.io/charts/cert-manager-v0.11.0.tgz : fetching now
...
Dependency https://charts.jetstack.io/charts/cert-manager-v0.11.0.tgz : successfully fetched
Dependency https://charts.jetstack.io/charts/cert-manager-v0.11.0.tgz : Content-Type application/x-compressed is not supported for unpack. Ignoring save # <---- this is just a warning

Compile error: vendor/charts/cert-manager for target: sandbox-labs not found in search_paths: ['/opt/mykapitan/vendor', '/opt/mykapitan']   # <-- this is the error, the artifact has not been extracted in vendor/charts
```

** If it's a bug (please complete the following information):**
 - `python --version`: `Python 3.7.8`
 - `pip3 --version`: `pip 20.1.1 from /opt/venv/lib/python3.7/site-packages/pip (python 3.7)`
 - `Are you using pyenv or virtualenv?` : probably virtualenv

**Additional context**

Using a custom docker image wrapping the 'kapitan:0.28' image.

Retrieving the artefact shows that the Content-Type header of the artifact is indeed `application/x-compressed`

```bash
wget -Sq -O/dev/null https://charts.jetstack.io/charts/cert-manager-v0.11.0.tgz 2>&1 | grep Content-Type
  Content-Type: application/x-compressed
```

I checked the existing issues and I found #691 which looks very close to my issue (even if the missing Content-Type is different than mine). Both my issue and #691 could be fixed at once by whitelisting the new Content-Types in https://github.com/kapicorp/kapitan/blob/master/kapitan/utils.py#L499
