### ISSUE TITLE
`null` at the begining of each yaml file rendered via helm binding integration

### ISSUE THREAD

**Issue by ofen** [kapicorp/kapitan#735]
**Describe the bug/feature**
Yaml files rendered via helm binding integration contains `null` at the beginning of each rendered file e.g.

```yaml
null
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/instance: foobar
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: foobar
    helm.sh/chart: foobar-v1
  name: foobar
  namespace: default
spec:
  jobTemplate:
    spec:
       ...
```

**To Reproduce**
1. Install kapitan and helm binding from master
```bash
git clone https://github.com/kapicorp/kapitan.git && \
  cd kapitan/ && \
  git submodule init  && \
  git submodule update && \
  make build_helm_binding && \
  pip3 install .
```
2. Create dummy chart via `helm create foobar` in `.charts/` directory
3. Create class
```yaml
---
parameters:
  kapitan:
    compile:
    - output_path: charts/
      input_type: helm
      input_paths:
      - .charts/foobar
      helm_values:
        foo: bar
      helm_params:
        namespace: default
        release_name: foobar
```
4. Add class to target
5. Compile `kapitan compile`
6. Open `./compiled/${target}/charts/foobar/templates`
7. Open any `yaml` file

**Expected behavior**
No `null` values at the beginning of rendered files
