### ISSUE TITLE
[Feature] Allow to decide when Kapitan renders the secrets

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#738]
# Describe the feature
When using the helm "provider" of kapitan, the secrets cannot be injected. The reason seams to be that kapitan doesn't inject the secrets into helm rendering.

# To Reproduce

```yaml
$ cat inventory/class/artifactory.yml
parameters:
  artifactory:
    secret:
      accessAdmin:
        secret: ?{base64:targets/${target_name}/accessAdmin_secret||randomstr}

  artifactory:
    chart_name: artifactory
    chart_version: 8.4.0
    namespace: ${namespace}
    helm_values:
      name: artifactory
      artifactory:
        accessAdmin:
          secret: ${artifactory:secret:accessAdmin:secret]

  kapitan:
    dependencies:
    - type: https
      output_path: components/charts/
      source: https://charts.jfrog.io/artifactory/helm/artifactory-${artifactory:chart_version}.tgz
      unpack: True

    compile:
    - input_type: helm
      input_paths:
        - components/charts/artifactory
      output_path: .
      helm_params:
        namespace: ${artifactory:namespace}
        release_name: ${artifactory:chart_name}
      helm_values: ${artifactory:helm_values} 
```
```yaml
$ cat compiled/artifactory/artifactory/templates/secret.yml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: artifactory
    chart: artifactory-11.9.4
    heritage: Tiller
    release: artifactory
  name: artifactory-artifactory-access-config
stringData:
  access.config.patch.yml: "security:\n  tls: false\n secret: P3tiYXNlNjQ6dGFyZ2V0cy8vYWNjZXNzQWRtaW5fc2VjcmV0fHxyYW5kb21zdHJ9Cg=\n"
type: Opaque
```
```bash
$ echo "P3tiYXNlNjQ6dGFyZ2V0cy8ke3RhcmdldF9uYW1lfS9hY2Nlc3NBZG1pbl9zZWNyZXR8fHJhbmRvbXN0cn0=" | base64 -d
?{base64:targets/${target_name}/accessAdmin_secret||randomstr}
```

`./kapitan compile`
# Expected behavior
1. Kapitan generates the secrets
2. injects them into the helm building process
