### ISSUE TITLE
Compiling the same jsonnet multiple times in different classes

### ISSUE THREAD

**Issue by ddvogt** [kapicorp/kapitan#750]
**Describe the bug/feature**
Is there a way to reuse the same jsonnet definition in multiple inventory classes? In other words, can I define a cluster in the inventory and use it in different flavors? If so, I cannot figure out how. 

**To Reproduce**
Consider the following definitions:

`target/dev.myl`:
```YAML
classes:
  - cluster_a
  - cluster_b

parameters:
  kapitan:
    vars:
      target: dev
```

`inventory/cluster_a.yml`:
```YAML
parameters:
  app_version: version_a
  kapitan:
    compile:
      - output_path: ${app_version}
        input_type: jsonnet
        output_type: json
        prune: True
        input_paths:
          - components/cluster.jsonnet
```

`inventory/cluster_b.yml`:
```YAML
parameters:
  app_version: version_b
  kapitan:
    compile:
      - output_path: ${app_version}
        input_type: jsonnet
        output_type: json
        prune: True
        input_paths:
          - components/cluster.jsonnet
```

**Expected behavior**
My expectation was to find two folders in `compiled/dev/version_a|b` both with a spark-driver.json.

Instead, I only find the last class instantiated and the following json:

`compiled/dev/version_b.json`:
```json
{
  "apiVersion": "apps/v1",
  "kind": "StatefulSet",
  "metadata": {
    "name": "version_b"
  }
}
```

I was expecting another file for `version_a`. I assume that this is either my fault since I did not use the Kapitan correctly or it is by design since the inventory is generated only once and the parameter `app_version` is overwritten by the second class import. If it is by design, I'd really appreciate how to solve this. 

Note: It would be possible to store both versions in a different parameter but this would result in changes in the jsonnet definition. In particular, I have to differentiate between the parameters in the template, which seems rather hacky. 

Thanks in advance!
