### ISSUE TITLE
Secrets of type `plain` are not accessible during the compile time

### ISSUE THREAD

**Issue by bdnf** [kapicorp/kapitan#762]
**Describe the bug/feature**
Secrets of type **plain** are not accessible during the compile time in `jsonnet` files.
Hardcoded variables from parameters are accessible as expected.
Though the behaviour might be intended for refs of type **AWS KMS**, **Vaultkv**, etc. the behaviour for types **plain** or **env** should allow to access files during the compile time.

**To Reproduce**

1. Assuming simple folder structure:
```text
├── components
|   └── test-component.jsonnet
└── inventory
    └── classes
    |       └── base.yml
    └── targets
            └── microserviceyml
```

2. Contents of *components/test-component.jsonnet*:
```jsonnet
local kap = import 'lib/kapitan.libjsonnet';
local inventory = kap.inventory();

local TOPIC = inventory.parameters.arguments.topic;
assert TOPIC == "starting_offsets.TIER1": "topic strings don't match"; # assertion fail here
assert std.asciiLower(TOPIC) == "starting_offsets.tier1": "lowercase topic strings don't match";

local database = std.asciiLower(inventory.parameters.arguments.mysql);
assert database == "some-slq-database": "strings don't match";

{
  'job': {
    apiVersion: 'batch/v1',
    kind: 'Job',
    metadata: {
      labels: {
        database: database,
        topic: std.asciiLower(TOPIC),
        deployment_name: inventory.parameters.deployment_name,
      },
      name: database + '-' + std.asciiLower(TOPIC),
    },
    spec: {}
  }
}
```

3. Contents of *inventory/classes/base.yaml*:
```yaml
parameters:
  arguments:
    mysql: some-slq-DATABASE
    topic: ?{plain:topic}

  kapitan:
    compile:
      - output_path: .
        input_type: jsonnet
        output_type: json
        prune: True
        input_paths:
          - components/test-component.jsonnet

```
4. Contents of *inventory/targets/microservice.yaml*:
```yaml
classes:
  - base

parameters:
  deployment_name: dev
  target_namespace: default

  commit_tag: 1223456789

  kapitan:
    vars:
      target: microservice

```

5. Set the reference of type **plain**:
```bash
echo -n "starting_offsets.TIER1" | kapitan refs  --write plain:topic -t  microservice -f -
```

6. Output is:
```bash
kapitan compile -t microservice 

Jsonnet error: failed to compile /src/kapitan/components/test-component.jsonnet:
 RUNTIME ERROR: topic strings don't match
	/src/kapitan/components/test-component.jsonnet:(5:1)-(25:2)	

Compile error: failed to compile target: microservice
```

**Expected behavior**
Compiled successfully and compiled file to be *compiled/microservice/job.json* with contents:
```json
{
  "apiVersion": "batch/v1",
  "kind": "Job",
  "metadata": {
    "labels": {
      "database": "some-slq-database",  # works fine
      "deployment_name": "dev",
      "topic": "starting_offsets.TIER1".  # should be lowercase
    },
    "name": "some-slq-database-starting_offsets.TIER1"  # should be lowercase
  }
}
```

** If it's a bug (please complete the following information):**
 - `python --version`: Python 3.7.11
 - `pip3 --version`: pip 21.2.2 from /opt/venv/lib/python3.7/site-packages/pip (python 3.7)
 - `pyenv`

**Additional context**

It would be nice to access variables that are set dynamically via **plain** ref type during the compile time.
For example Kubernetes resources require that fields are lowercased and do not contain some special characters.

Additionally, it is not impossible to use `plain:variable` as a generated file name. The output file name is simple shown as:

```text
compiled/microservice/job-?{plain:variable}.json
```
instead of:
```text
compiled/microservice/job-non-secret.json
```
