### ISSUE TITLE
Matching variables in multiple classes are overridden incorrectly

### ISSUE THREAD

**Issue by bdnf** [kapicorp/kapitan#785]
**Describe the bug/feature**
I believe multiple matching variables in multiple classes are overridden incorrectly. Obviously, the latest class referenced - *wins* here.

Not sure if this expected behaviour, however it is very confusing, and such bugs would be really hard to find when many classes are defined and compiled.
If this is expected, the fact should be well documented.

**To Reproduce**

1. Assuming simple folder structure:
```text
├── components
 |   └── mysql.jsonnet
 |   └── server.jsonnet
└── inventory
    └── classes
    |       └── mysql.yml
    |       └── server.yml
    └── targets
            └── microservice.yml
```

2. Contents of *components/mysql.jsonnet*:
```jsonnet
local kap = import 'lib/kapitan.libjsonnet';
local inventory = kap.inventory();

{
  'db': {
    apiVersion: 'v1',
    kind: 'Pod',
    metadata: {
      labels: {
        version: inventory.parameters.version_tag,
      },
      name: inventory.parameters.name,
    },
    spec: {}
  }
}
```

3. Contents of *components/server.jsonnet*:
```jsonnet
local kap = import 'lib/kapitan.libjsonnet';
local inventory = kap.inventory();

{
  'pod': {
    apiVersion: 'v1',
    kind: 'Job',
    metadata: {
      labels: {
        version: inventory.parameters.version_tag,
      },
      name: inventory.parameters.name,
    },
    spec: {}
  }
}
```

4. Contents of *inventory/classes/mysql.yaml*:
```yaml
parameters:
  version_tag: 11111
  name: database

  kapitan:
    compile:
    - output_path: .
      input_type: jsonnet
      output_type: yaml
      input_paths:
        - components/mysql.jsonnet
```

5. Contents of *inventory/classes/server.yaml*:
```yaml
parameters:
  # Note, no version_tag here !!! 
  name: test-service # note the name !!!

  kapitan:
    compile:
      - output_path: .
        input_type: jsonnet
        output_type: yaml
        input_paths:
          - components/server.jsonnet
```

6. Contents of *inventory/targets/microservice.yaml*:
```yaml
classes:
  - mysql
  - server

parameters:
  # version_tag: 999 # <- if enabled, overrides variable as expected, for all classes
  kapitan:
    vars:
      target: microservice

```

7. Output is:
```bash
kapitan compile -t microservice 
Compiled microservice (0.07s)
```
Output files:

Mysql:
```yaml
# compiled/microservice/db.yaml
apiVersion: v1
kind: Pod # <- correct
metadata:
  labels:
    version: 11111  # correct
  name: test-service   # Error! should be `database`
spec: {}
```

Server:
```yaml
# compiled/microservice/server.yaml
apiVersion: v1
kind: Job  # <- correct
metadata:
  labels:
    version: 11111 # Error! should fail or be empty?
  name: test-service
spec: {}
```

**Expected behavior**
Fields `name` and `labels.version` should differ in output files for the same target.
Files are not overridden, as it can be seen from the output.

** Possible Bug **
 - `kapitan --version`: 0.29.5
 - `python --version`: Python 3.8.11
 - `pip3 --version`: pip 21.2.4
 - `pyenv`

**Comment by Moep90** [comment]
Can be confirmed on `kapicorp/kapitan:v0.30.0-rc.0` as well

**Comment by ademariag** [comment]
Hello @bdnf and @Moep90,

The behavior you observe is expected.
The parameters you set in each class (`name` and `version_tag`) are set at the root of the inventory (just under `parameters`).

When the inventory is compiled, the `parameters.name` from the class you imported last (`server`) will override one previously defined in `mysql`.

in the case of `parameters.version`, as the parameter is missing completely from the `server` class, the inventory will keep the one defined in `mysql`.

Although confusing for new users, this is the intended behavior. 
If you want to use a different one for each component, please use something like

```
parameters:
  mysql:
    name: mysql_service
    version: 1111
  server:
    name: server_service
```

and change the `jsonnet` code accordingly.

Keep repeating this for N components, and the duplicated code will inevitably push you towards the use of generators, which is our recommended approach.
