### ISSUE TITLE
[Feature] add binaryData field to Configmaps

### ISSUE THREAD

**Issue by EugenFo** [kapicorp/kapitan#787]
**Describe the feature**
A configmap can take a data or binaryData field. Kapitan only allows the data field.

**Expected behavior**
When defining an "config_maps" dict, I would love to see that I can choose between "data" and "binaryData".
So something like:
```yaml
config_maps:
  data-config:
    mount: /path/data
    readOnly: true
    data:
      application.yml:
        template: some_template.j2
        values: ${config}
  binardata-config:
    mount: /path/binarydata
    readOnly: true
    binaryData:
      keystore.jks:
        template: another_template.j2
        values: ${another_config}
```
And maybe add another option to let kapitan encode the template to base64 before writing it into the configmap.

Thank you!
