### ISSUE TITLE
`jinja2` output objects for single files should allow file renaming or strip `.j2` suffix

### ISSUE THREAD

**Issue by deepbrook** [kapicorp/kapitan#790]
**Describe the bug/feature**
The `output_path` field of compile objects does not behave as one would expect: when specifying a path to a file, it is treated as a directory instead. Alternatively, `kapitan` should strip `.j2` extension of jinja template files.

**To Reproduce**
Compiling an arbitrary file `state.yaml.j2` with the following compile object:
```yaml
parameters:
  kapitan:
    compile:
      - input_type: "jinja2"
        input_paths: ["components/acls/state.yaml.j2"]
        output_path: "acls/"
```
results in an output file named `state.yaml.j2`.

Modifying the output path to be an explicit file (not using a trailing slash) like so:

```yaml
parameters:
  kapitan:
    compile:
      - input_type: "jinja2"
        input_paths: ["components/acls/state.yaml.j2"]
        output_path: "acls/state.yaml"
```
Results in an output file written to `acls/state.yaml/state.yaml.j2`.

**Expected behavior**
When rendering a single file, I expect `kapitan` to treat the value of `output_path` as a path to a single file (`path/to/file`), *unless* it ends in a trailing slash (`path/to/dir/`). 

Alternatively, when using the `jinja2` input type, I would expect `kapitan` to strip a present `.j2` extension automatically. 

Examples:
- `state.yaml.j2` becomes `state.yaml`
- `state.yaml.j2.j2` becomes `state.yaml.j2` (i.e. remove `pathlib.Path.stem`.

Possible solution:

Using `pathlib.Path.with_stem()` would take care of dropping the suffix safely:
```python
>>>import pathlib  # built-in
>>>fpath = pathlib.Path("state.yaml.j2")
>>>fpath.stem == ".j2"  # Check if path is a jinja template
True
>>>fpath.with_stem("")  # Strip single .j2 extension
state.yaml
>>>pathlib.Path("state.yaml.j2.j2").with_stem("")  # Replace last .j2 extensions correctly
state.yaml.j2
```

** If it's a bug (please complete the following information):**
```
❯ python --version
Python 3.8.10
❯pip --version
pip 21.0.1 from /home/deepbrook/.virtualenvs/vod-msk-cluster/lib/python3.8/site-packages/pip (python 3.8)
❯ kapitan --version
0.30.0rc0
