### ISSUE TITLE
Ability to strip .j2 extension when performing jinja2 compilation and potentially fully rename

### ISSUE THREAD

**Issue by KostasKgr** [kapicorp/kapitan#805]
**Describe the feature**
Ability to strip .j2 extension when performing jinja2 compilation.
It is useful to have .j2 extension on files for at least two reasons:
- IDEs provide syntax highlighting
- People know it is a jinja2 template file without having to read through it

If a file path is specified for output_path then this gets interpreted as a folder name.
https://kapitan.dev/compile/#specifying-inputs-and-outputs

Perhaps general renaming would cover more use cases, such as compiling a template to multiple outputs in the same node or providing a better semantic name to the template.

Raising this after discussing stripping .j2 in kapitan slack channel.

I don't have some good recommendation on how to approach it, as the current interface of compile expects multiple input files and one output directory.
Perhaps ansible template module can be used for inspiration: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html

**To Reproduce**
```
parameters:
  kapitan:
    compile:
    - output_path: app/my_app1/config.cfg
      input_type: jinja2
      input_paths:
        - templates/generic_python_config.cfg.j2
      input_params:
      	name: my_app1
      	# ...
```

Output of the above would be compiled to app/my_app1/config.cfg/generic_python_config.cfg.j2

**Expected behavior**
Able to drop .j2 extension and rename.
Ouput would be compiled to app/my_app1/config.cfg

**Additional context**
Using kapicorp/kapitan:v0.30.0-rc.0
