### ISSUE TITLE
[Helm] invalid Yaml document separator: null

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#843]
# Describe the bug/feature
When rendering the `kube-prometheus-stack` chart, I get the following issue while applying the manifest:

invalid Yaml document separator: null

# To Reproduce

1. Define the chart with the values below
2. `./kapitan compile --fetch`
3. `kubectl apply --recursive -f compiled/..../kube-prometheus-stack.yml`

## Values
```yaml
parameters:
  kube-prometheus-stack:
    application_version: 0.57.0
    chart_name: kube-prometheus-stack
    chart_version: 36.2.1
    fullname: kube-prometheus-stack
    helm_params:
      name: kube-prometheus-stack
    helm_values:
      alertmanager:
        enabled: false
        podAntiAffinityTopologyKey: kubernetes.io/hostname
        securityContext:
          fsGroup: 2000
          runAsGroup: 2000
          runAsNonRoot: true
          runAsUser: 1000
      coreDns:
        enabled: true
      defaultRules:
        create: false
        rules:
          alertmanager: true
          configReloaders: true
          etcd: true
          general: true
          k8s: true
          kubeApiserverAvailability: true
          kubeApiserverBurnrate: true
          kubeApiserverHistogram: true
          kubeApiserverSlos: true
          kubePrometheusGeneral: true
          kubePrometheusNodeRecording: true
          kubeProxy: true
          kubeScheduler: true
          kubeStateMetrics: true
          kubelet: true
          kubernetesApps: true
          kubernetesResources: true
          kubernetesStorage: true
          kubernetesSystem: true
          network: true
          node: true
          nodeExporterAlerting: true
          nodeExporterRecording: true
          prometheus: true
          prometheusOperator: true
      global:
        rbac:
          create: true
          pspEnabled: true
      grafana:
        enabled: false
        serviceMonitor:
          interval: 30s
          scheme: http
          scrapeTimeout: 30s
          tlsConfig: {}
      kubeApiServer:
        enabled: true
        tlsConfig:
          insecureSkipVerify: false
          serverName: kubernetes
      kubeControllerManager:
        enabled: true
      kubeEtcd:
        enabled: true
      kubeProxy:
        enabled: true
      kubeScheduler:
        enabled: true
      kubelet:
        enabled: true
        namespace: kube-system
      nameOverride: kube-prometheus-stack
      namespaceOverride: monitoring
      prometheus:
        enabled: true
        prometheusSpec:
          logFormat: json
          logLevel: info
          podAntiAffinityTopologyKey: kubernetes.io/hostname
          resources:
            limit:
              memory: 2048Mi
          retention: 2h
          shards: null
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 50Gi
                storageClassName: ceph-block
        securityContext:
          fsGroup: 2000
          runAsGroup: 2000
          runAsNonRoot: true
          runAsUser: 1000
        serviceAccount:
          create: true
        thanosService:
          enabled: true
        thanosServiceMonitor:
          enabled: true
      prometheusOperator:
        admissionWebhooks:
          enabled: false
        containerSecurityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        enabled: true
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 1m
          memory: 1Mi
        resources: null
        securityContext:
          fsGroup: 65534
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        serviceAccount:
          create: true
    logformat: json
    loglevel: info
    namespace: monitoring
    persistence:
      retention:
        size: '10'
        time: 2h
      storageclass: ceph-block

  # -------------------------------------------------
  # HELM RENDER DEFINITION
  # -------------------------------------------------
  kapitan:
    dependencies:
      - type: helm
        output_path: components/charts/${kube-prometheus-stack:chart_name}/${kube-prometheus-stack:chart_version}/${kube-prometheus-stack:application_version}
        source: https://prometheus-community.github.io/helm-charts
        version: ${kube-prometheus-stack:chart_version}
        chart_name: ${kube-prometheus-stack:chart_name}
    compile:
      - input_type: helm
        input_paths:
          - components/charts/${kube-prometheus-stack:chart_name}/${kube-prometheus-stack:chart_version}/${kube-prometheus-stack:application_version}
        output_path: k8s/${kube-prometheus-stack:namespace}
        helm_params:
          namespace: ${kube-prometheus-stack:namespace}
          name: ${kube-prometheus-stack:chart_name}
          output_file: ${kube-prometheus-stack:chart_name}.yml
        helm_values: ${kube-prometheus-stack:helm_values}
```

**Expected behavior**
There should be no diff between the helmchart template command and the kapitan output.

```
$ python --version
Python 3.7.12
```

```
$ pip3 --version
pip 22.1.2 from /opt/venv/lib/python3.7/site-packages/pip (python 3.7)
```

# Additional context

I opened a Bug on the helm-chart but it was not reproducable

[prometheus-community/helm-charts/issues/2239](https://github.com/prometheus-community/helm-charts/issues/2239)

**Comment by Moep90** [comment]
With #844 I was able to manage at least to change the behavior.

I now get the following, which can be deployed via kubectl.
```yaml
[...]
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
---
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
[...]
```
