### ISSUE TITLE
Support formatted YAML outputs for multiline yamls

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#852]
**Support formatted YAML outputs for multiline yamls**

In this examole I used the thanos [helmchart](https://github.com/bitnami/charts/tree/master/bitnami/thanos/)

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: thanos-objstore
  name: thanos-objstore
stringData:
  objstore.yml: "type: S3\nconfig:\n  bucket: my-bucket\n  endpoint: s3.example.com\n\
    \  region: eu-de\n  access_key: ?{vaultkv:ey......:embedded}\n\
    \  secret_key: ?{vaultkv:ey.......19:embedded}\n\
    \  http_config:\n    insecure_skip_verify: false\n"
type: Opaque
```
Should look like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: thanos-objstore
  name: thanos-objstore
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: my-bucket
      endpoint: s3.example.com
      region: eu-de
      access_key: ?{vaultkv:..............:embedded}    
      secret_key: ?{vaultkv:..............:embedded}    
      http_config:
        insecure_skip_verify: false
type: Opaque

```
