### ISSUE TITLE
Git dependency and git modules 

### ISSUE THREAD

**Issue by metacoma** [kapicorp/kapitan#914]
**Describe the bug/feature**
As i can understand, at this moment there is no way to clone git repository with git submodules?

**To Reproduce**
1. define dependency, for example, `kapicorp/kapitan` git repository
```yaml
---
parameters: 
  kapitan:
    dependencies:
       - type: git 
         output_path: files/git/github/kapicorp/kapitan
         source: https://github.com/kapicorp/kapitan
         ref: master
```
2.
 ```bash
$ kapitan compile --fetch
```

3. Try to open `.gitmodules` file https://github.com/kapicorp/kapitan/blob/master/.gitmodules
```bash
$ ls -ltr files/git/github/kapicorp/kapitan/.gitmodule
ls: cannot access 'files/git/github/kapicorp/kapitan/.gitmodule': No such file or directory
```

**Expected behavior**
`kapicorp/kapitan` github repository must be cloned with git modules (in this case with https://github.com/kapicorp/reclass.git)

**Additional context**
As far as i understand, `kapitan` uses GitPython library to clone git repos. Probably, the properly submodule handling in GitPython will helps https://gitpython.readthedocs.io/en/0.3.3/tutorial.html#submodule-handling

Also, submodule option might be added into dependency definition, like
```yaml
---
parameters: 
  kapitan:
    dependencies:
       - type: git
         submodule: True 
         output_path: files/git/github/kapicorp/kapitan
         source: https://github.com/kapicorp/kapitan
         ref: master
```
