### ISSUE TITLE
Simplify input type Helm

### ISSUE THREAD

**Issue by gburiola** [kapicorp/kapitan#977]
At the moment, in order to use `input_type: helm` we need to declare all of this:

```
parameters:

  kapitan:

    dependencies:
    - type: https
      source: https://<REPO_NAME>/<CHART_NAME>-<VERSION>.tgz
      unpack: True
      output_path: .charts

    compile:
      - output_path: my_dir
        input_type: helm
        input_paths:
          - .charts/<CHART_NAME>
        helm_values:
          key1: value1
        helm_params:
          name: my_release
          namespace: my_namespace
```

I propose we simplify the above, by removing the external dependency and using the helm cli directly to fetch the chart.

```
parameters:

  kapitan:

    compile:
      - output_path: my_dir
        input_type: helm
        helm_values:
          key1: value1
        helm_params:
          name: my_release
          namespace: my_namespace
          repo: <REPO_NAME>
          chart: <CHART_NAME>
          version: <VERSION>
```

We can do that by using the helm cli flags `--repo <REPO_NAME> --version <VERSION> <CHART_NAME>`
This would be done [in this file here](https://github.com/kapicorp/kapitan/blob/master/kapitan/inputs/helm.py#L215-L221)

### Benefits

1. Simplified inventory code
2. No more locally fetched charts inside `output_path: .charts`
3. In addition to the direct benefits listed above, it also allows us to use multiple different chart versions. At the moment this is not possible, because dependencies are extracted to ` <OUTPUT_PATH>/<CHART_NAME>`. So if you fetch 2 different versions of the same chart they will overwrite each other.
