### ISSUE TITLE
More control over input type Helm output_path

### ISSUE THREAD

**Issue by gburiola** [kapicorp/kapitan#978]
At the moment, when using code below:

```
  kapitan:
    compile:
      - output_path: my_dir
        input_type: helm
        input_paths:
          - .charts/<CHART_NAME>
```

The compiled output will be under `compiled/<TARGET_NAME>/my_dir/<CHART_NAME>/templates`

I proposed we get rid of the `<CHART_NAME>/templates` that is automatically added at the end of the `output_path`.

The additional path is added by the helm CLI when locally rendering the templates.

This can be easily fixed by kapitan when copying from the TMP_FOLDER to the COMPILED_FOLDER

So the kapitan config above would output files to `compiled/<TARGET_NAME>/my_dir/`

This is a breaking change, but people who want to continue with the same behaviour can just explicitly add the extra path to their `output_path`
